### ISSUE TITLE
ActionView::Template::Error (undefined method `children' for nil:NilClass)

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1285]
From groups:
After upgrading from 2.2.7 to 2.3.1, I am getting a 500 error on the actual server gui that says "Something went wrong. Rest assured, you have been assigned 0% of the blame."

So far this only happens in 1 feed, but I will be testing it in others.

Installed using apt-get on ubuntu.

Here is the error I get in /var/log/apache2/error.log:
```
App 12516 stderr: ** [Airbrake] Success: Net::HTTPOK
App 12516 stderr:
App 12516 stderr: ActionView::Template::Error (undefined method `children' for nil:NilClass):
App 12516 stderr:     1: <div class="tile<% unless submission.content.children.empty? %> tile-stack<% end %>" data-submission-id="<%= submission.id %>">
App 12516 stderr:     2:   <%= link_to [submission.feed, submission], :class => "tile-content" do %>
App 12516 stderr:     3:     <%= render_content(submission.content, {:type => 'tile'}) %>
App 12516 stderr:     4:
App 12516 stderr:   app/views/submissions/_submission_tile.html.erb:1:in `_app_views_submissions__submission_tile_html_erb__3906644533564743768_44304860'
App 12516 stderr:   app/views/submissions/_index_body.html.erb:186:in `block in _app_views_submissions__index_body_html_erb__3492203619809220758_46670740'
App 12516 stderr:   app/views/submissions/_index_body.html.erb:185:in `each'
App 12516 stderr:   app/views/submissions/_index_body.html.erb:185:in `_app_views_submissions__index_body_html_erb__3492203619809220758_46670740'
App 12516 stderr:   app/views/submissions/index.html.erb:6:in `_app_views_submissions_index_html_erb___1888457661993994339_45379140'
App 12516 stderr:   app/controllers/application_controller.rb:112:in `set_time_zone'
App 12516 stderr:
App 12516 stderr:
App 12516 stderr: Processing by ErrorsController#render_error as HTML
App 12516 stderr:   Parameters: {"state"=>"denied", "feed_id"=>"2"}
App 12516 stderr: Completed 200 OK in 57ms (Views: 0.6ms | ActiveRecord: 15.7ms)
App 12516 stderr:   Rendered errors/error_generic.html.erb within layouts/no-topmenu (2.5ms)
App 12516 stderr:   Rendered elements/_head.html.erb (0.2ms)
App 12516 stderr: Completed 500 Internal Server Error in 76ms (Views: 8.5ms | ActiveRecord: 24.0ms)
```

**Comment by augustf** [comment]
It looks to me like someone had a submission with no content object. We can do a check for this, but it seems like this shouldn't have been allowed via the UI.
